druid:
  url: jdbc:mysql://mdb:3306/smile?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  driver-class: com.mysql.jdbc.Driver
  username: smile
  password: smile
  initial-size: 1
  min-idle: 1
  max-active: 20
  druid.test-on-borrow: true
server:
  port: 8443
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
spring:
  servlet:
    multipart:
      max-file-size: -1
redis:
  host:
    ip: 192.168.1.69
    port: 16378
mail:
  host: smtp.sina.com
  port: 25
  user: test_gfire
  pass: xujiao0923
  from: test_gfire@sina.com
  ssl: false

#undertown配置
# 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#server.undertow.io-threads: 4
# 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
#server.undertow.worker-threads: 20
# 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
# 每块buffer的空间大小,越小的空间被利用越充分
#server.undertow.buffer-size: 1024
# 是否分配的直接内存
#server.undertow.direct-buffers: true


#logging.file: myapplication.log